- name: Open port in firewall for DNS
  ansible.posix.firewalld:
    port: "53/udp"
    permanent: yes
    immediate: yes
    state: enabled
    zone: "{{ item }}"
  loop:
    - libvirt

- name: Open port in firewall for DHCP
  ansible.posix.firewalld:
    port: "67/udp"
    permanent: yes
    immediate: yes
    state: enabled
    zone: "{{ item }}"
  loop:
    - libvirt

- name: Open port in firewall for PXE
  ansible.posix.firewalld:
    port: "69/udp"
    permanent: yes
    immediate: yes
    state: enabled
    zone: "{{ item }}"
  loop:
    - libvirt
