---
- name: 'Default to linuxefi'
  set_fact:
    use_boot_image: false
    efi_boot_command: "efi"

- name: Get SUT details
  uri:
    url: "http://{{ jumpbox }}.{{ domain }}:{{ provision_port }}/systems/{{ system.value.fqdn }}"
    method: GET
  register: system_details

- name: 'Register SUT CPU arch variable'
  set_fact:
    system_arch: "{{ system_details.json[system.value.fqdn].arch }}"

- name: 'Arch tags'
  set_fact:
    arch_tags: "{{ arch_tags| default([]) + [ system_arch ] }}"

- name: Alternate EFI
  set_fact:
    efi_boot_command: ""
  when:
    - system.value.alternate_efi_boot_commands| default(false, true) | bool

- name: Use EFI bootloader image (x86 and aarch64)
  set_fact:
    use_boot_image: true
  when:
    - system_arch == 'x86_64' or system_arch == 'aarch64'
    - system.value.efi | default(False, true) | bool

- name: Use powerpc-ieee1275 bootloader image (ppc64le)
  set_fact:
    use_boot_image: true
  when:
    - system_arch == 'ppc64le'
    - not system.value.petitboot | default(False, true) | bool

- name: Get First Variant
  set_fact:
    boot_variant: "{{ compose_info.boot_variants.keys()| first }}"

- name: Get Variant Compose
  set_fact:
    boot: "{{ compose_info.boot_variants[boot_variant] }}"

- name: Generate tree_url
  ansible.builtin.set_fact:
    tree_url: "http://{{ jumpbox }}.{{ domain }}:{{ http_store_port }}/{{ boot[system_arch].os_tree |replace('/data','') }}"

# curl -d '{"action": "provision", "kernel_url": "http://okd-master-0:8080/RHEL-8.9/compose/BaseOS/x86_64/os/images/pxeboot/vmlinuz", "initrd_url": "http://okd-master-0:8080/RHEL-8.9/compose/BaseOS/x86_64/os/images/pxeboot/initrd.img"}' -X POST -H 'Content-Type: application/json' http://localhost:8000/systems/sut1.dci.local/actions

- name: Provision System
  uri:
    url: "http://{{ jumpbox }}.{{ domain }}:{{ provision_port }}/systems/{{ system.value.fqdn }}/actions"
    method: POST
    body:
      action: "provision"
      kernel_url: "{{ tree_url }}{{ boot[system_arch].pxe_images.kernel }}"
      initrd_url: "{{ tree_url }}{{ boot[system_arch].pxe_images.initrd }}"
      image_url: "{{ tree_url }}{{ boot[system_arch].pxe_images.image }}"
      use_boot_image: "{{ use_boot_image }}"
      kernel_options: "grub2_postfix={{ efi_boot_command }} {{ system.value.kernel_options | default(kernel_options| default('')) }}"
      ks_meta:
        osmajor: "{{ compose_info.osmajor }}"
        osminor: "{{ compose_info.osminor }}"
        tree_url: "{{ tree_url }}"
        repos: "{{ boot[system_arch].repos }}"
        ks_appends: ""
    body_format: json
    headers:
      Accept: application/json
      Content-Type: application/json
    status_code: [201, 409]
  changed_when: provision.status == 201
  register: provision

- name: Wait for Install job to initiate
  uri:
    url: "http://{{ jumpbox }}.{{ domain }}:{{ provision_port }}/jobs/{{ provision.json.job }}"
    method: GET
    status_code:
      - 200
  until: uri_output.status == 200
  retries: 24 # Retries for 24 * 5 seconds = 120 seconds = 2 minutes
  delay: 5 # Every 5 seconds
  register: uri_output
