---
- name: Update all packages on the system
  become: true
  dnf:
    name: "*"
    state: latest

- name: Install beaker client repo
  become: true
  copy:
    src: beaker-client.repo
    dest: /etc/yum.repos.d/beaker-client.repo

- name: Install needed packages
  become: true
  yum:
    name:
      - beaker-client
    state: present
