jumpbox: "{{ ansible_hostname }}"
provisioner_dir: "{{ lab.provisioner_dir }}"
containers:
  - name: dci-provisioner
    service: container-provisioner.service
    image: quay.io/p3ck/dci-provisioner:latest
    ports:
      - "8000"
  - name: dci-lab
    service: container-lab.service
    image: quay.io/p3ck/dci-lab:latest
    volumes:
      - "{{ provisioner_dir }}/tftpboot:/opt/tftpboot:z"
      - "{{ provisioner_dir }}/templates:/opt/templates:z"
    ports:
      - "69"
      - "8008"
  - name: redis
    service: container-redis.service
    image: docker.io/redislabs/redismod:latest
    command:
      - "--dir"
      - "/data"
    volumes:
      - "{{ provisioner_dir }}/redis:/data:z"
    ports:
      - "6379"
file_owner: "{{ ansible_env.USER }}"
file_group: "{{ file_owner }}"
dns_servers: []
extra_config: {}
